config/routes.rb
Rails.application.routes.draw do

  post '/query', to: "main#query"
  post '/api/query', to: "api#query"
  post '/api/specific_query', to: "api#specific_query"
  post '/api/update_current_qth', to: "api#update_current_qth"
  post '/api/user_callsign_info', to: "api#user_callsign_info"
  get '/show', to: "main#show"
  get '/new', to: "main#new"
  post '/create', to: "main#create"
  get '/edit', to: "main#edit"
  put '/update', to: "main#update"
  get '/predestroy', to: "main#predestroy"
  delete '/destroy', to: "main#destroy"
  get '/auth/:provider/callback', to: "main#omniauth_callback", as: :omniauth_callback
  get '/logout', to: "main#logout"

  root to: "main#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    before_filter :find_user
    before_filter :user_only, only: [:new, :create, :show, :edit, :update, :predestroy, :destroy, :logout]

    def index

    end

    def query
        @users = RemoteUser.like(params[:callsign_query]).with_info.order(:callsign)
    end

    def new
        if !@user.callsign_info.nil?
            flash[:error] = t("errors.info_already_entered")
            redirect_to edit_path
        end
        @info = CallsignInfo.new
    end

    def create
        if !@user.callsign_info.nil?
            flash[:error] = t("errors.info_already_entered")
            redirect_to edit_path
        end
        @info = CallsignInfo.create(info_params)
        if @info.new_record?
            flash[:error] = t("errors.error_while_saving") + ": " + @info.errors.full_messages.join(", ")
            redirect_to new_path
        else
            flash[:success] = t("success.info_created")
            redirect_to show_path
        end
    end

    def show
        if @user.callsign_info.nil?
            flash[:error] = t("errors.info_not_entered")
            redirect_to root_path
        end
    end

    def edit
        if @user.callsign_info.nil?
            flash[:error] = t("errors.info_not_entered")
            redirect_to new_path
        end
        @info = @user.callsign_info
    end

    def update
        if @user.callsign_info.nil?
            flash[:error] = t("errors.info_not_entered")
            redirect_to new_path
        end
        @info = @user.callsign_info
        if @info.update_attributes(info_params)
            flash[:success] = t("success.info_updated")
            redirect_to show_path
        else
            flash[:error] = t("errors.error_while_saving") + ": " + @info.errors.full_messages.join(", ")
            redirect_to edit_path
        end
    end

    def predestroy
        if @user.callsign_info.nil?
            flash[:error] = t("errors.info_not_entered")
            redirect_to root_path
        end
    end

    def destroy
        if @user.callsign_info.nil?
            flash[:error] = t("errors.info_not_entered")
            redirect_to root_path
        end
        if @user.callsign_info.destroy
            flash[:success] = t("success.info_destroyed")
            redirect_to root_path
        else
            flash[:error] = t("errors.error_while_destroying")
            redirect_to predestroy_path
        end
    end

    def omniauth_callback
        if !auth_hash.nil?
            @user = RemoteUser.find_by_callsign(auth_hash.info.callsign)
            if @user.nil?
                @user = RemoteUser.create(callsign: auth_hash.info.callsign, email: auth_hash.info.email)
                @user.reload
            end
            @session = RemoteSession.new
            @session.token = auth_hash.credentials.token
            @session.token_expires = Time.at(auth_hash.credentials.expires_at)
            @session.refresh_token = auth_hash.credentials.refresh_token
            @session.remote_user = @user
            @session.save!
            @user.save!
            session['remote_session_token'] = @session.token
        end
        redirect_to root_path
    end

    def logout
        HTTParty.post("https://rlauth.phitherek.me/oauth/revoke?token=#{@session.token}")
        @session.destroy
        session.delete('remote_session_token')
        redirect_to root_path
    end

    private

    def auth_hash
        request.env['omniauth.auth']
    end

    def find_user
        if session['remote_session_token'] != nil
            @session = RemoteSession.find_by_token(session['remote_session_token'])
            if !@session.nil?
                @user = @session.remote_user
                @check = JSON.parse(HTTParty.get("https://rlauth.phitherek.me/api/user_data?access_token=#{@session.token}").body || "{}")
                if @check.include?("status") && @check["status"] == "failure"
                    session['remote_session_token'] = nil
                    redirect_to '/auth/rlauth' and return
                elsif @check.include?("user")
                    @user = RemoteUser.find_by_callsign(@check["user"]["callsign"])
                    if !@user.nil?
                        session['remote_session_token'] = @session.token
                    else
                        session['remote_session_token'] = nil
                    end
                end
            else
                @user = nil
            end
        else
            @user = nil
        end
    end

    def user_only
        redirect_to root_path unless !@user.nil?
    end

    def info_params
        params.require(:callsign_info).permit(:name, :stationary_qth, :stationary_qth_locator, :current_qth, :current_qth_locator, :remote_user_id)
    end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/edit.html.haml
%h2= t(".edit_info")
= form_for @info, url: update_path, method: :put do |f|
  .row
    = f.label :name
    = f.text_field :name
  .row
    = f.label :stationary_qth
    = f.text_field :stationary_qth
  .row
    = f.label :stationary_qth_locator
    = f.text_field :stationary_qth_locator
  .row
    = f.label :current_qth
    = f.text_field :current_qth
  .row
    = f.label :current_qth_locator
    = f.text_field :current_qth_locator
  .row
    = f.hidden_field :remote_user_id, value: @user.id
    = f.submit t(:submit)
= link_to t(:back), root_path

app/views/main/index.html.haml
%h2= t(".database_query")
= form_tag query_path do
  = label_tag :callsign_query, t(".callsign") + ":"
  = text_field_tag :callsign_query
  = submit_tag t(".query")

app/views/main/new.html.haml
%h2= t(".new_info")
= form_for @info, url: create_path do |f|
  .row
    = f.label :name
    = f.text_field :name
  .row
    = f.label :stationary_qth
    = f.text_field :stationary_qth
  .row
    = f.label :stationary_qth_locator
    = f.text_field :stationary_qth_locator
  .row
    = f.label :current_qth
    = f.text_field :current_qth
  .row
    = f.label :current_qth_locator
    = f.text_field :current_qth_locator
  .row
    = f.hidden_field :remote_user_id, value: @user.id
    = f.submit t(".add_to_database")
= link_to t(:back), root_path

app/views/main/predestroy.html.haml
%h2= t(".destroy_info")
= button_to t(".delete_from_database"), destroy_path, method: :delete

app/views/main/query.html.haml
%h2= t(".query_results_for", query: params[:callsign_query])
- if @users.empty?
  %p.empty= t(".no_results")
- else
  %table
    %thead
      %tr
        %th= t(".callsign")
        %th= t(".name")
        %th= t(".stationary_qth")
        %th= t(".stationary_qth_locator")
        %th= t(".current_qth")
        %th= t(".current_qth_locator")
    %tbody
      - @users.each do |u|
        %tr
          %td= u.callsign
          %td= u.callsign_info.name
          %td= u.callsign_info.stationary_qth
          %td= u.callsign_info.stationary_qth_locator
          %td= (u.callsign_info.current_qth.nil? || u.callsign_info.current_qth.empty?) && (u.callsign_info.current_qth_locator.nil? || u.callsign_info.current_qth_locator.empty?) ? u.callsign_info.stationary_qth : u.callsign_info.current_qth
          %td= (u.callsign_info.current_qth.nil? || u.callsign_info.current_qth.empty?) && (u.callsign_info.current_qth_locator.nil? || u.callsign_info.current_qth_locator.empty?) ? u.callsign_info.stationary_qth_locator : u.callsign_info.current_qth_locator
= link_to t(:back), root_path

app/views/main/show.html.haml
%h2= t(".your_info")
%dl
  %dt= t(".callsign") + ":"
  %dd= @user.callsign
  %dt= t(".name") + ":"
  %dd= @user.callsign_info.name
  %dt= t(".stationary_qth") + ":"
  %dd= @user.callsign_info.stationary_qth
  %dt= t(".stationary_qth_locator") + ":"
  %dd= @user.callsign_info.stationary_qth_locator
  %dt= t(".current_qth") + ":"
  %dd= @user.callsign_info.current_qth
  %dt= t(".current_qth_locator") + ":"
  %dd= @user.callsign_info.current_qth_locator
  %dt= t(".shown_current_qth") + ":"
  %dd= (@user.callsign_info.current_qth.nil? || @user.callsign_info.current_qth.empty?) && (@user.callsign_info.current_qth_locator.nil? || @user.callsign_info.current_qth_locator.empty?) ? @user.callsign_info.stationary_qth : @user.callsign_info.current_qth
  %dt= t(".shown_current_qth_locator") + ":"
  %dd= (@user.callsign_info.current_qth.nil? || @user.callsign_info.current_qth.empty?) && (@user.callsign_info.current_qth_locator.nil? || @user.callsign_info.current_qth_locator.empty?) ? @user.callsign_info.stationary_qth_locator : @user.callsign_info.current_qth_locator
= link_to t(:back), root_path