config/routes.rb
Rails.application.routes.draw do

  post '/query', to: "main#query"
  post '/api/query', to: "api#query"
  post '/api/specific_query', to: "api#specific_query"
  post '/api/update_current_qth', to: "api#update_current_qth"
  post '/api/user_callsign_info', to: "api#user_callsign_info"
  get '/show', to: "main#show"
  get '/new', to: "main#new"
  post '/create', to: "main#create"
  get '/edit', to: "main#edit"
  put '/update', to: "main#update"
  get '/predestroy', to: "main#predestroy"
  delete '/destroy', to: "main#destroy"
  get '/auth/:provider/callback', to: "main#omniauth_callback", as: :omniauth_callback
  get '/logout', to: "main#logout"

  root to: "main#index"
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RLCallsign
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %h1 RLCallsign
      %p= t(:subtitle)
    - if flash[:success]
      .flash.success
        = flash[:success]
    - if flash[:notice]
      .flash.notice
        = flash[:notice]
    - if flash[:error]
      .flash.error
        = flash[:error]
    .userbox
      - if @user.nil?
        %p= t(:not_logged_in)
        = link_to t(:login), "/auth/rlauth"
      - else
        %p= t(:logged_in_as, callsign: @user.callsign)
        - if @user.callsign_info.nil?
          = link_to t(:new_info), new_path
        - else
          = link_to t(:show_info), show_path
          = link_to t(:edit_info), edit_path
          = link_to t(:destroy_info), predestroy_path
        = link_to t(:logout), logout_path
    .main
      = yield
    %footer
      %p.created_by= t(:created_by)
      %p.radiolog= t(:radiolog_tools)